import 'con.dart';
import 'medical.dart';

final List<Pet> pets = [
  Pet(
    name: 'Buddy',
    type: 'Dog',
    description: 'Buddy is a friendly and energetic golden retriever who enjoys playing fetch and going for long walks. He gets along well with children and other pets, making him a wonderful family companion.',
    imagePath: 'assets/pet_images/dog1.jpg',
    breed: 'Golden Retriever',
    age: 5,
    color: 'Golden',
    gender: 'Male',
    medicalHistory: [
      MedicalHistory(date: DateTime(2024, 1, 15), description: 'Annual vaccination', eventType: 'Vaccination'),
      MedicalHistory(date: DateTime(2024, 6, 10), description: 'Routine check-up', eventType: 'Check-up'),
    ],
  ),
  Pet(
    name: 'Whiskers',
    type: 'Cat',
    description: 'Whiskers is a playful and affectionate Siamese cat who loves to explore and interact with her surroundings. She has a sweet personality and enjoys spending time with her human friends.',
    imagePath: 'assets/pet_images/cat1.jpg',
    breed: 'Siamese',
    age: 3,
    color: 'Cream',
    gender: 'Female',
    medicalHistory: [
      MedicalHistory(date: DateTime(2024, 3, 5), description: 'Feline leukemia vaccination', eventType: 'Vaccination'),
    ],
  ),
  Pet(
    name: 'Charlie',
    type: 'Parrot',
    description: 'Charlie is a colorful and lively parrot with a knack for mimicking sounds and entertaining his human companions. His vibrant feathers and cheerful demeanor make him a charming pet.',
    imagePath: 'assets/pet_images/parrot.jpg',
    breed: 'African Grey',
    age: 2,
    color: 'Grey',
    gender: 'Male',
    medicalHistory: [
      MedicalHistory(date: DateTime(2024, 4, 22), description: 'Beak and feather disease screening', eventType: 'Screening'),
    ],
  ),
  Pet(
    name: 'Bella',
    type: 'Dog',
    description: 'Bella is a gentle and loving Labrador retriever who enjoys cuddling and playing with her favorite toys. She is great with kids and other pets, and she loves to be part of family activities.',
    imagePath: 'assets/pet_images/dog2.jpg',
    breed: 'Labrador Retriever',
    age: 4,
    color: 'Black',
    gender: 'Female',
    medicalHistory: [
      MedicalHistory(date: DateTime(2024, 2, 18), description: 'Heartworm prevention', eventType: 'Prevention'),
    ],
  ),
  Pet(
    name: 'Luna',
    type: 'Cat',
    description: 'Luna is a beautiful and affectionate Persian cat who loves to lounge and be pampered. Her luxurious fur and sweet personality make her an ideal companion for anyone looking for a loving lap cat.',
    imagePath: 'assets/pet_images/cat2.jpg',
    breed: 'Persian',
    age: 6,
    color: 'White',
    gender: 'Female',
    medicalHistory: [
      MedicalHistory(date: DateTime(2024, 5, 30), description: 'Annual vet check-up', eventType: 'Check-up'),
    ],
  ),
  Pet(
    name: 'Max',
    type: 'Rabbit',
    description: 'Max is a friendly and curious rabbit who loves to hop around and explore. He enjoys fresh vegetables and is a great pet for families with children due to his gentle nature.',
    imagePath: 'assets/pet_images/rabbit.jpg',
    breed: 'Holland Lop',
    age: 1,
    color: 'Brown',
    gender: 'Male',
    medicalHistory: [
      MedicalHistory(date: DateTime(2024, 7, 15), description: 'Routine dental check', eventType: 'Dental Check'),
    ],
  ),
  Pet(
    name: 'Oliver',
    type: 'Bird',
    description: 'Oliver is a cheerful canary who brings a touch of nature into your home with his melodious songs. His green and yellow plumage adds a vibrant splash of color to any space.',
    imagePath: 'assets/pet_images/bird.jpg',
    breed: 'Canary',
    age: 2,
    color: 'Green & Yellow',
    gender: 'Male',
    medicalHistory: [
      MedicalHistory(date: DateTime(2024, 8, 1), description: 'Feather inspection', eventType: 'Inspection'),
    ],
  ),
  Pet(
    name: 'Daisy',
    type: 'Dog',
    description: 'Daisy is an energetic Beagle puppy who loves to play and explore. She has a friendly personality and gets along well with everyone she meets, making her a wonderful addition to any home.',
    imagePath: 'assets/pet_images/dog3.jpg',
    breed: 'Beagle',
    age: 1,
    color: 'Tricolor',
    gender: 'Female',
    medicalHistory: [
      MedicalHistory(date: DateTime(2024, 9, 10), description: 'Initial vaccination', eventType: 'Vaccination'),
    ],
  ),
  Pet(
    name: 'Milo',
    type: 'Cat',
    description: 'Milo is a playful Bengal cat with a striking coat and a lively personality. He enjoys interactive play and is affectionate towards his human companions, making him a delightful pet.',
    imagePath: 'assets/pet_images/cat3.jpg',
    breed: 'Bengal',
    age: 3,
    color: 'Spotted Brown',
    gender: 'Male',
    medicalHistory: [
      MedicalHistory(date: DateTime(2024, 10, 5), description: 'Feline distemper vaccination', eventType: 'Vaccination'),
    ],
  ),
  Pet(
    name: 'Ginger',
    type: 'Hamster',
    description: 'Ginger is a small and energetic golden hamster who enjoys running on her wheel and exploring her habitat. She is a low-maintenance pet and is perfect for small living spaces.',
    imagePath: 'assets/pet_images/hamster.jpg',
    breed: 'Syrian',
    age: 1,
    color: 'Golden',
    gender: 'Female',
    medicalHistory: [
      MedicalHistory(date: DateTime(2024, 11, 12), description: 'Routine health check', eventType: 'Check-up'),
    ],
  ),
  Pet(
    name: 'Penny',
    type: 'Ferret',
    description: 'Penny is an inquisitive and playful ferret who loves to explore and interact with her surroundings. Her energetic nature and playful antics make her a fun and engaging pet.',
    imagePath: 'assets/pet_images/ferret.jpg',
    breed: 'Domestic',
    age: 2,
    color: 'White & Brown',
    gender: 'Female',
    medicalHistory: [
      MedicalHistory(date: DateTime(2024, 12, 20), description: 'Ferret wellness check', eventType: 'Check-up'),
    ],
  ),
  Pet(
    name: 'Rocky',
    type: 'Dog',
    description: 'Rocky is a strong and protective Rottweiler with a loyal heart. He is affectionate with his family and is an excellent guard dog, providing both companionship and security.',
    imagePath: 'assets/pet_images/dog4.jpg',
    breed: 'Rottweiler',
    age: 6,
    color: 'Black & Tan',
    gender: 'Male',
    medicalHistory: [
      MedicalHistory(date: DateTime(2024, 2, 22), description: 'Hip and elbow check', eventType: 'Check-up'),
    ],
  ),
];

